name: Build and Run



on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]



jobs:

  build:



    runs-on: ubuntu-latest



    steps:

    - uses: actions/checkout@v2

    

    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck

      

    - name: build Reciever
      run: g++ -Wall -Wextra -Werror --coverage -o testreciever Receiver/lib/*.cpp
  
    - name: build Sender
      run: g++ -Wall -Wextra -Werror --coverage -o testsender Sender/lib/*.cpp
      
    - name: build receiverTestApplication
      run: g++ -Wall -Wextra -Werror --coverage -o receiverTestapp Receiver/ReceiverTest/*.cpp
    - name: move gcno to receiver test dir
      run: mv *.gcno Receiver/ReceiverTest/    
      
    - name: build senderTestApplication
      run: g++ -Wall -Wextra -Werror --coverage -o senderTestapp Sender/SenderTest/*.cpp
         

    - name: Reciever static analysis
      run:  cppcheck Receiver/lib/ --error-exitcode=1.
      

    - name: run
      run: ./testsender sample-review/review-report.csv | ./testreciever

    - name: run receiverTestApplication
      run: ./receiverTestapp
    - name: move .gcda files to receiver test dir
      run:  mv *.gcda Receiver/ReceiverTest/
      
    - name: run senderTestApplication
      run: ./senderTestapp

    - name: receiver coverage report
      run:  gcov -r Receiver/ReceiverTest/*.cpp
