name: Build and Run



on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]



jobs:

  build:



    runs-on: ubuntu-latest



    steps:

    - uses: actions/checkout@v2

    

    - name: install cppcheck static analysis

      run: sudo apt-get update && sudo apt-get install -y cppcheck

      

    - name: build Reciever

      run: g++ -Wall -Wextra -Werror --coverage -o testreciever Receiver/lib/*.cpp
      
    - name: build Sender
      run: g++ -Wall -Wextra -Werror --coverage -o testsender Sender/lib/*.cpp
      

    - name: static analysis

      run:  cppcheck Receiver/lib/ --error-exitcode=1.
      

    - name: run

      run: ./testsender | ./testreciever

    

    - name: coverage report

      run: gcov -r *.cpp
